# Portfolio Assessment2
## Duc Thuan Tran 104330455

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.decomposition import PCA
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from scipy import integrate
from scipy.signal import find_peaks
import os

# Step 1: Data Collection

### Boning.csv

In [5]:
boning_df = pd.read_csv('ampc2/boning.csv')

In [6]:
boning_df.shape

(54180, 67)

In [7]:
boning_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54180 entries, 0 to 54179
Data columns (total 67 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Frame              54180 non-null  int64
 1   L5 x               54180 non-null  float64
 2   L5 y               54180 non-null  float64
 3   L5 z               54180 non-null  float64
 4   L3 x               54180 non-null  float64
 5   L3 y               54180 non-null  float64
 6   L3 z               54180 non-null  float64
 7   T12 x              54180 non-null  float64
 8   T12 y              54180 non-null  float64
 9   T12 z              54180 non-null  float64
 10  T8 x               54180 non-null  float64
 11  T8 y               54180 non-null  float64
 12  T8 z               54180 non-null  float64
 13  Neck x             54180 non-null  float64
 14  Neck y             54180 non-null  float64
 15  Neck z             54180 non-null  float64
 16  Head x             54180 non-null  float64
 17  Head y             54180 non-null  float64
 18  Head z             54180 non-null  float64
 19  Right Shoulder x   54180 non-null  float64
 20  Right Shoulder y   54180 non-null  float64
 21  Right Shoulder z   54180 non-null  float64
 22  Right Upper Arm x  54180 non-null  float64
 23  Right Upper Arm y  54180 non-null  float64
 24  Right Upper Arm z  54180 non-null  float64
 25  Right Forearm x    54180 non-null  float64
 26  Right Forearm y    54180 non-null  float64
 27  Right Forearm z    54180 non-null  float64
 28  Right Hand x       54180 non-null  float64
 29  Right Hand y       54180 non-null  float64
 30  Right Hand z       54180 non-null  float64
 31  Left Shoulder x    54180 non-null  float64
 32  Left Shoulder y    54180 non-null  float64
 33  Left Shoulder z    54180 non-null  float64
 34  Left Upper Arm x   54180 non-null  float64
 35  Left Upper Arm y   54180 non-null  float64
 36  Left Upper Arm z   54180 non-null  float64
 37  Left Forearm x     54180 non-null  float64
 38  Left Forearm y     54180 non-null  float64
 39  Left Forearm z     54180 non-null  float64
 40  Left Hand x        54180 non-null  float64
 41  Left Hand y        54180 non-null  float64
 42  Left Hand z        54180 non-null  float64
 43  Right Upper Leg x  54180 non-null  float64
 44  Right Upper Leg y  54180 non-null  float64
 45  Right Upper Leg z  54180 non-null  float64
 46  Right Lower Leg x  54180 non-null  float64
 47  Right Lower Leg y  54180 non-null  float64
 48  Right Lower Leg z  54180 non-null  float64
 49  Right Foot x       54180 non-null  float64
 50  Right Foot y       54180 non-null  float64
 51  Right Foot z       54180 non-null  float64
 52  Right Toe x        54180 non-null  float64
 53  Right Toe y        54180 non-null  float64
 54  Right Toe z        54180 non-null  float64
 55  Left Upper Leg x   54180 non-null  float64
 56  Left Upper Leg y   54180 non-null  float64
 57  Left Upper Leg z   54180 non-null  float64
 58  Left Lower Leg x   54180 non-null  float64
 59  Left Lower Leg y   54180 non-null  float64
 60  Left Lower Leg z   54180 non-null  float64
 61  Left Foot x        54180 non-null  float64
 62  Left Foot y        54180 non-null  float64
 63  Left Foot z        54180 non-null  float64
 64  Left Toe x         54180 non-null  float64
 65  Left Toe y         54180 non-null  float64
 66  Left Toe z         54180 non-null  float64
dtypes: float64(66), int64(1)
memory usage: 27.7 MB

In [8]:
boning_df.describe()

,Frame,L5 x,L5 y,L5 z,L3 x,L3 y,L3 z,T12 x,T12 y,T12 z,...,Left Upper Leg z,Left Lower Leg x,Left Lower Leg y,Left Lower Leg z,Left Foot x,Left Foot y,Left Foot z,Left Toe x,Left Toe y,Left Toe z
count,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,...,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000,54180.000000
mean,27089.500000,-0.004635,-0.000110,0.003835,-0.005254,0.000970,0.005874,-0.005874,0.002050,0.007912,...,-0.019230,0.003445,-0.008191,-0.007893,-0.004595,0.004648,-0.005782,-0.001711,0.004516,0.002089
std,15640.563129,0.670811,0.566650,0.434615,0.960774,0.795684,0.615253,1.253266,1.028811,0.798510,...,0.725964,1.323737,1.497188,0.690409,1.721424,1.193410,1.084819,1.684979,1.189246,1.074874
min,0.000000,-9.529681,-11.050340,-5.469383,-13.745627,-15.926846,-7.818795,-17.961573,-20.803352,-10.225488,...,-12.208943,-22.596462,-29.606227,-21.340287,-49.250083,-28.082640,-24.859754,-36.543737,-26.660149,-24.721795
25%,13544.750000,-0.227320,-0.177936,-0.144189,-0.322647,-0.248738,-0.204484,-0.418456,-0.319794,-0.265078,...,-0.206531,-0.380573,-0.494484,-0.186468,-0.348061,-0.316125,-0.217815,-0.346676,-0.316855,-0.205948
50%,27089.500000,-0.003885,0.006770,0.001380,-0.004432,0.010191,0.002568,-0.003918,0.014029,0.004139,...,-0.006699,-0.005292,0.002966,-0.003856,-0.014317,0.005533,0.008176,-0.015485,0.004969,0.014001
75%,40634.250000,0.223235,0.200544,0.151893,0.317472,0.282270,0.214741,0.413233,0.364757,0.279794,...,0.181934,0.355966,0.487547,0.168172,0.287229,0.332724,0.243013,0.286848,0.332680,0.245344
max,54179.000000,14.950358,9.819392,8.911717,21.592190,14.172133,10.501353,28.234023,18.524873,13.728549,...,10.755519,20.546986,19.930001,13.468850,42.949162,30.498145,26.118296,41.990168,29.772758,25.546454

In [9]:
boning_df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['Frame', 'L5 x', 'L5 y', 'L5 z', 'L3 x', 'L3 y', 'L3 z', 'T12 x',
       'T12 y', 'T12 z', 'T8 x', 'T8 y', 'T8 z', 'Neck x', 'Neck y', 'Neck z',
       'Head x', 'Head y', 'Head z', 'Right Shoulder x', 'Right Shoulder y',
       'Right Shoulder z', 'Right Upper Arm x', 'Right Upper Arm y',
       'Right Upper Arm z', 'Right Forearm x', 'Right Forearm y',
       'Right Forearm z', 'Right Hand x', 'Right Hand y', 'Right Hand z',
       'Left Shoulder x', 'Left Shoulder y', 'Left Shoulder z',
       'Left Upper Arm x', 'Left Upper Arm y', 'Left Upper Arm z',
       'Left Forearm x', 'Left Forearm y', 'Left Forearm z', 'Left Hand x',
       'Left Hand y', 'Left Hand z', 'Right Upper Leg x', 'Right Upper Leg y',
       'Right Upper Leg z', 'Right Lower Leg x', 'Right Lower Leg y',
       'Right Lower Leg z', 'Right Foot x', 'Right Foot y', 'Right Foot z',
       'Right Toe x', 'Right Toe y', 'Right Toe z', 'Left Upper Leg x',
       'Left Upper Leg y', 'Left Upper Leg z', 'Left Lower Leg x',
       'Left Lower Leg y', 'Left Lower Leg z', 'Left Foot x', 'Left Foot y',
       'Left Foot z', 'Left Toe x', 'Left Toe y', 'Left Toe z'],
      dtype='object')>

In [10]:
boning_df.duplicated().sum()

0

In [11]:
boning_df.isnull().sum()

Frame          0
L5 x           0
L5 y           0
L5 z           0
L3 x           0
              ..
Left Foot y    0
Left Foot z    0
Left Toe x     0
Left Toe y     0
Left Toe z     0
Length: 67, dtype: int64

### Slicing.csv

In [13]:
slicing_df = pd.read_csv('ampc2/slicing.csv')

In [14]:
slicing_df.shape

(17880, 67)

In [15]:
slicing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 67 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Frame              17880 non-null  int64
 1   L5 x               17880 non-null  float64
 2   L5 y               17880 non-null  float64
 3   L5 z               17880 non-null  float64
 4   L3 x               17880 non-null  float64
 5   L3 y               17880 non-null  float64
 6   L3 z               17880 non-null  float64
 7   T12 x              17880 non-null  float64
 8   T12 y              17880 non-null  float64
 9   T12 z              17880 non-null  float64
 10  T8 x               17880 non-null  float64
 11  T8 y               17880 non-null  float64
 12  T8 z               17880 non-null  float64
 13  Neck x             17880 non-null  float64
 14  Neck y             17880 non-null  float64
 15  Neck z             17880 non-null  float64
 16  Head x             17880 non-null  float64
 17  Head y             17880 non-null  float64
 18  Head z             17880 non-null  float64
 19  Right Shoulder x   17880 non-null  float64
 20  Right Shoulder y   17880 non-null  float64
 21  Right Shoulder z   17880 non-null  float64
 22  Right Upper Arm x  17880 non-null  float64
 23  Right Upper Arm y  17880 non-null  float64
 24  Right Upper Arm z  17880 non-null  float64
 25  Right Forearm x    17880 non-null  float64
 26  Right Forearm y    17880 non-null  float64
 27  Right Forearm z    17880 non-null  float64
 28  Right Hand x       17880 non-null  float64
 29  Right Hand y       17880 non-null  float64
 30  Right Hand z       17880 non-null  float64
 31  Left Shoulder x    17880 non-null  float64
 32  Left Shoulder y    17880 non-null  float64
 33  Left Shoulder z    17880 non-null  float64
 34  Left Upper Arm x   17880 non-null  float64
 35  Left Upper Arm y   17880 non-null  float64
 36  Left Upper Arm z   17880 non-null  float64
 37  Left Forearm x     17880 non-null  float64
 38  Left Forearm y     17880 non-null  float64
 39  Left Forearm z     17880 non-null  float64
 40  Left Hand x        17880 non-null  float64
 41  Left Hand y        17880 non-null  float64
 42  Left Hand z        17880 non-null  float64
 43  Right Upper Leg x  17880 non-null  float64
 44  Right Upper Leg y  17880 non-null  float64
 45  Right Upper Leg z  17880 non-null  float64
 46  Right Lower Leg x  17880 non-null  float64
 47  Right Lower Leg y  17880 non-null  float64
 48  Right Lower Leg z  17880 non-null  float64
 49  Right Foot x       17880 non-null  float64
 50  Right Foot y       17880 non-null  float64
 51  Right Foot z       17880 non-null  float64
 52  Right Toe x        17880 non-null  float64
 53  Right Toe y        17880 non-null  float64
 54  Right Toe z        17880 non-null  float64
 55  Left Upper Leg x   17880 non-null  float64
 56  Left Upper Leg y   17880 non-null  float64
 57  Left Upper Leg z   17880 non-null  float64
 58  Left Lower Leg x   17880 non-null  float64
 59  Left Lower Leg y   17880 non-null  float64
 60  Left Lower Leg z   17880 non-null  float64
 61  Left Foot x        17880 non-null  float64
 62  Left Foot y        17880 non-null  float64
 63  Left Foot z        17880 non-null  float64
 64  Left Toe x         17880 non-null  float64
 65  Left Toe y         17880 non-null  float64
 66  Left Toe z         17880 non-null  float64
dtypes: float64(66), int64(1)
memory usage: 9.1 MB

In [16]:
slicing_df.shape

(17880, 67)

In [17]:
slicing_df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['Frame', 'L5 x', 'L5 y', 'L5 z', 'L3 x', 'L3 y', 'L3 z', 'T12 x',
       'T12 y', 'T12 z', 'T8 x', 'T8 y', 'T8 z', 'Neck x', 'Neck y', 'Neck z',
       'Head x', 'Head y', 'Head z', 'Right Shoulder x', 'Right Shoulder y',
       'Right Shoulder z', 'Right Upper Arm x', 'Right Upper Arm y',
       'Right Upper Arm z', 'Right Forearm x', 'Right Forearm y',
       'Right Forearm z', 'Right Hand x', 'Right Hand y', 'Right Hand z',
       'Left Shoulder x', 'Left Shoulder y', 'Left Shoulder z',
       'Left Upper Arm x', 'Left Upper Arm y', 'Left Upper Arm z',
       'Left Forearm x', 'Left Forearm y', 'Left Forearm z', 'Left Hand x',
       'Left Hand y', 'Left Hand z', 'Right Upper Leg x', 'Right Upper Leg y',
       'Right Upper Leg z', 'Right Lower Leg x', 'Right Lower Leg y',
       'Right Lower Leg z', 'Right Foot x', 'Right Foot y', 'Right Foot z',
       'Right Toe x', 'Right Toe y', 'Right Toe z', 'Left Upper Leg x',
       'Left Upper Leg y', 'Left Upper Leg z', 'Left Lower Leg x',
       'Left Lower Leg y', 'Left Lower Leg z', 'Left Foot x', 'Left Foot y',
       'Left Foot z', 'Left Toe x', 'Left Toe y', 'Left Toe z'],
      dtype='object')>

slicing_df.columns

In [19]:
slicing_df.duplicated().sum()

0

In [20]:
slicing_df.isnull().sum()

Frame          0
L5 x           0
L5 y           0
L5 z           0
L3 x           0
              ..
Left Foot y    0
Left Foot z    0
Left Toe x     0
Left Toe y     0
Left Toe z     0
Length: 67, dtype: int64

## Columns Extracting

In [22]:
columns_to_extract = ['Frame', 
                     'Right Upper Leg x', 'Right Upper Leg y', 'Right Upper Leg z',
                     'Left Upper Leg x', 'Left Upper Leg y', 'Left Upper Leg z']

boning_extracted_df = boning_df[columns_to_extract].copy()
slicing_extracted_df = slicing_df[columns_to_extract].copy()

boning_extracted_df['class'] = 0
slicing_extracted_df['class'] = 1

combined_df = pd.concat([boning_extracted_df, slicing_extracted_df], ignore_index = True)

combined_df.to_csv('combined_data_step1.csv', index=False)

# Step 2: Composite Columns

In [24]:
df = pd.read_csv('combined_data_step1.csv')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72060 entries, 0 to 72059
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Frame              72060 non-null  int64
 1   Right Upper Leg x  72060 non-null  float64
 2   Right Upper Leg y  72060 non-null  float64
 3   Right Upper Leg z  72060 non-null  float64
 4   Left Upper Leg x   72060 non-null  float64
 5   Left Upper Leg y   72060 non-null  float64
 6   Left Upper Leg z   72060 non-null  float64
 7   class              72060 non-null  int64
dtypes: float64(6), int64(2)
memory usage: 4.4 MB

In [26]:
df.shape

(72060, 8)

In [27]:
df = df.rename(columns={
    'Frame': 'frame',
    'Right Upper Leg x': 'right_leg_x',
    'Right Upper Leg y': 'right_leg_y',
    'Right Upper Leg z': 'right_leg_z',
    'Left Upper Leg x': 'left_leg_x',
    'Left Upper Leg y': 'left_leg_y',
    'Left Upper Leg z': 'left_leg_z'
})

# 1. Root mean square value of x and y
df['rms_xy_right'] = np.sqrt((df['right_leg_x']**2 + df['right_leg_y']**2) /2)
df['rms_xy_left'] = np.sqrt((df['left_leg_x']**2 + df['left_leg_y']**2) /2)

# 2. Root mean square value of y and z
df['rms_yz_right'] = np.sqrt((df['right_leg_y']**2 + df['right_leg_z']**2) /2)
df['rms_yz_left'] = np.sqrt((df['left_leg_y']**2 + df['left_leg_z']**2) /2)

# 3. Root mean square value of z and x
df['rms_zx_right'] = np.sqrt((df['right_leg_z']**2 + df['right_leg_x']**2) /2)
df['rms_zx_left'] = np.sqrt((df['left_leg_z']**2 + df['left_leg_x']**2) /2)

# 4. Root mean square value of x y z
df['rms_xyz_right'] = np.sqrt((df['right_leg_x']**2 + df['right_leg_y']**2 + df['right_leg_z']**2) / 3)
df['rms_xyz_left'] = np.sqrt((df['left_leg_x']**2 + df['left_leg_y']**2 + df['left_leg_z']**2) / 3)

# 5. Roll calculation
df['roll_right'] = 180 * np.arctan2(df['right_leg_y'], 
                                     np.sqrt(df['right_leg_x']**2 + df['right_leg_z']**2)) / np.pi
df['roll_left'] = 180 * np.arctan2(df['left_leg_y'], 
                                    np.sqrt(df['left_leg_x']**2 + df['left_leg_z']**2)) / np.pi
# 6. Pitch calculation
df['pitch_right'] = 180 * np.arctan2(df['right_leg_x'], 
                                      np.sqrt(df['right_leg_y']**2 + df['right_leg_z']**2)) / np.pi
df['pitch_left'] = 180 * np.arctan2(df['left_leg_x'], 
                                     np.sqrt(df['left_leg_y']**2 + df['left_leg_z']**2)) / np.pi

df = df.to_csv('combined_data_step2.csv',index=False)

# Step 3: Data Preprocessing & Feature Computation

In [29]:
df = pd.read_csv('combined_data_step2.csv')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72060 entries, 0 to 72059
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   frame          72060 non-null  int64
 1   right_leg_x    72060 non-null  float64
 2   right_leg_y    72060 non-null  float64
 3   right_leg_z    72060 non-null  float64
 4   left_leg_x     72060 non-null  float64
 5   left_leg_y     72060 non-null  float64
 6   left_leg_z     72060 non-null  float64
 7   class          72060 non-null  int64
 8   rms_xy_right   72060 non-null  float64
 9   rms_xy_left    72060 non-null  float64
 10  rms_yz_right   72060 non-null  float64
 11  rms_yz_left    72060 non-null  float64
 12  rms_zx_right   72060 non-null  float64
 13  rms_zx_left    72060 non-null  float64
 14  rms_xyz_right  72060 non-null  float64
 15  rms_xyz_left   72060 non-null  float64
 16  roll_right     72060 non-null  float64
 17  roll_left      72060 non-null  float64
 18  pitch_right    72060 non-null  float64
 19  pitch_left     72060 non-null  float64
dtypes: float64(18), int64(2)
memory usage: 11.0 MB

In [31]:
df.shape

(72060, 20)

In [32]:
def compute_features(df_segment, column_name):
    features = {}
    
    # Mean
    features[f'mean_{column_name}'] = df_segment[column_name].mean()
    
    # Standard deviation
    features[f'std_{column_name}'] = df_segment[column_name].std()
    
    # Min and Max
    features[f'min_{column_name}'] = df_segment[column_name].min()
    features[f'max_{column_name}'] = df_segment[column_name].max()
    
    # Area under the curve (AUC) - using trapezoidal rule
    features[f'auc_{column_name}'] = integrate.trapz(df_segment[column_name].values)

    # Number of peaks
    # Using prominence parameter to avoid detecting noise as peaks
    peaks, _ = find_peaks(df_segment[column_name].values, prominence=0.1)
    features[f'peaks_{column_name}'] = len(peaks)
    
    return features
    
# Identify data columns to compute features 
feature_columns = [col for col in df.columns if col not in ['frame', 'class']]

feature_rows = []

# Process data in one-minute chunks (60 frames per minute)
for class_value in [0, 1]: 
    class_df = df[df['class'] == class_value]
    
    for i in range(0, len(class_df), 60):
        minute_df = class_df.iloc[i:i+60]
        if len(minute_df) < 60:  
            continue

        # Initialize a feature dictionary for this minute
        minute_features = {'class': class_value}
        
        # Calculate features for each column
        for column in feature_columns:
            column_features = compute_features(minute_df, column)
            minute_features.update(column_features)
        
        feature_rows.append(minute_features)

feature_df = pd.DataFrame(feature_rows)

feature_df.to_csv('combined_data_step3.csv', index=False)

/var/folders/yr/mm0xskxn61jfrkxwp3y0mc7w0000gn/T/ipykernel_52421/679355292.py:15: DeprecationWarning: 'scipy.integrate.trapz' is deprecated in favour of 'scipy.integrate.trapezoid' and will be removed in SciPy 1.14.0
  features[f'auc_{column_name}'] = integrate.trapz(df_segment[column_name].values)

# Step 4: Training

In [34]:
features_df = pd.read_csv('combined_data_step3.csv')

In [35]:
features_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1201 entries, 0 to 1200
Columns: 109 entries, class to peaks_pitch_left
dtypes: float64(90), int64(19)
memory usage: 1022.9 KB

In [36]:
features_df.shape

(1201, 109)

In [37]:
X = features_df.drop('class', axis=1)
y = features_df['class']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

def evaluate_model(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\n{model_name} Results:")
    print(f"Accuracy: {accuracy:.4f}")

    return accuracy
    
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42)

## 1. SVM With Train-Test Split (70/30)

In [39]:
svm = SVC(random_state=42)
svm.fit(X_train, y_train)
svm_tt = evaluate_model(svm, X_test, y_test, "SVM (Train-Test split)")

SVM (Train-Test split) Results:
Accuracy: 0.8975

## 2. SVM with 10-fold Cross-Validation

In [41]:
svm_cv = SVC(random_state=42)
cv_scores = cross_val_score(svm_cv, X_scaled, y, cv=10)
svm_cv = cv_scores.mean()
print(f"\nSVM with 10-fold Cross-Validation:")
print(f"CV Accuracy: {svm_cv:.4f}")

SVM with 10-fold Cross-Validation:
CV Accuracy: 0.8951

## 3. SVM with Hyperparameter Tuning

In [43]:
param_grid = {
    'C' : [0.1, 1, 10, 100],
    'gamma': ['scale', 'auto', 0.01, 0.001],
    'kernel': ['rbf', 'linear']
}
grid_search = GridSearchCV(SVC(random_state=42), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

print("\nSVM Hyperparameter Tuning Results:")
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best cross-validation score: {grid_search.best_score_:.4f}")

best_svm = grid_search.best_estimator_
svm_tuned_tt = evaluate_model(best_svm, X_test, y_test, "SVM Tuned (Train-Test Split)")
svm_tuned_cv = grid_search.best_score_

SVM Hyperparameter Tuning Results:
Best parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Best cross-validation score: 0.9000

SVM Tuned (Train-Test Split) Results:
Accuracy: 0.9058

## 4. SVM with Feature Selection

In [45]:
selector = SelectKBest(f_classif, k=10)
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

# Get selected feature names for reference
selected_indices = selector.get_support(indices=True)
selected_features = X.columns[selected_indices]
print("\nSelected Features:")
print(selected_features.tolist())

best_svm_fs = SVC(**grid_search.best_params_, random_state=42)
best_svm_fs.fit(X_train_selected, y_train)
svm_fs_tt = evaluate_model(best_svm_fs, X_test_selected, y_test, "SVM Tuned with Feature Selection")

Selected Features:
['peaks_right_leg_x', 'peaks_right_leg_z', 'peaks_left_leg_x', 'peaks_left_leg_y', 'peaks_left_leg_z', 'peaks_rms_xy_right', 'peaks_rms_zx_right', 'peaks_rms_zx_left', 'peaks_rms_xyz_right', 'peaks_pitch_right']

SVM Tuned with Feature Selection Results:
Accuracy: 0.8560

## 5. SVM with PCA

In [47]:
pca = PCA(n_components=10)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print(f"\nPCA Explained Variance: {sum(pca.explained_variance_ratio_):.4f}")

best_svm_pca = SVC(**grid_search.best_params_, random_state=42)
best_svm_pca.fit(X_train_pca, y_train)
svm_pca_tt = evaluate_model(best_svm_pca, X_test_pca, y_test, "SVM Tuned with PCA")

PCA Explained Variance: 0.7258

SVM Tuned with PCA Results:
Accuracy: 0.9003

## SVM Summary Table

In [49]:
svm_summary = pd.DataFrame({
    'SVM model': [
        ' Train-Test split (70/30)',
        ' 10-fold cross-validation',
        ' 1 and 2 with hyperparameter tuning',
        ' 1 and 2 with hyperparameter tuning and 10 best features',
        ' 1 and 2 with hyperparameter tuning and 10 principal components'
    ],
    'Train-test split': [
        f"{svm_tt:.2%}",
        "N/A",
        f"{svm_tuned_tt:.2%}",
        f"{svm_fs_tt:.2%}",
        f"{svm_pca_tt:.2%}"
    ],
    'Cross-validation': [
        "N/A",
        f"{svm_cv:.2%}",
        f"{svm_tuned_cv:.2%}",
        f"{svm_tuned_cv:.2%}",  
        f"{svm_tuned_cv:.2%}"   
    ]
})

print("\nSVM Models Summary Table")
svm_summary

SVM Models Summary Table

,SVM model,Train-test split,Cross-validation
0,Train-Test split (70/30),89.75%,N/A
1,10-fold cross-validation,N/A,89.51%
2,1 and 2 with hyperparameter tuning,90.58%,90.00%
3,1 and 2 with hyperparameter tuning and 10 bes...,85.60%,90.00%
4,1 and 2 with hyperparameter tuning and 10 pri...,90.03%,90.00%

# Other Models

## SGD Classifier

In [52]:
sgd = SGDClassifier(max_iter=1000, random_state=42)
sgd.fit(X_train, y_train)
sgd_tt = evaluate_model(sgd, X_test, y_test, "SGD Classifier")

SGD Classifier Results:
Accuracy: 0.8698

## SGD with Cross-Validatiton

In [54]:
sgd_cv = SGDClassifier(max_iter=1000, random_state=42)
sgd_cv_scores = cross_val_score(sgd_cv, X_scaled, y, cv=10)
sgd_cv = sgd_cv_scores.mean()
print(f"\nSGD Classifier with 10-fold Cross-Validation:")
print(f"CV Accuracy: {sgd_cv:.4f}")

SGD Classifier with 10-fold Cross-Validation:
CV Accuracy: 0.8402

## Random Forest

In [56]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
rf_tt = evaluate_model(rf, X_test, y_test, "Random Forest")

Random Forest Results:
Accuracy: 0.8837

## Random Forestt with Cross-Validation

In [58]:
rf_cv = RandomForestClassifier(n_estimators=100, random_state=42)
rf_cv_scores = cross_val_score(rf_cv, X_scaled, y, cv=10)
rf_cv = rf_cv_scores.mean()
print(f"\nRandom Forest with 10-fold Cross-Validation:")
print(f"CV Accuracy: {rf_cv:.4f}")

Random Forest with 10-fold Cross-Validation:
CV Accuracy: 0.8718

## MLP Neural Network

In [60]:
mlp = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42)
mlp.fit(X_train, y_train)
mlp_tt = evaluate_model(mlp, X_test, y_test, "MLP Neural Network")

MLP Neural Network Results:
Accuracy: 0.8809

## MLP Neural Network with Cross-Validation

In [62]:
mlp_cv = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42)
mlp_cv_scores = cross_val_score(mlp_cv, X_scaled, y, cv=10)
mlp_cv = mlp_cv_scores.mean()
print(f"\nMLP Neural Network with 10-fold Cross-Validation:")
print(f"CV Accuracy: {mlp_cv:.4f}")

MLP Neural Network with 10-fold Cross-Validation:
CV Accuracy: 0.8842

## Other Classifiers Summary Table

In [64]:
all_models_summary = pd.DataFrame({
    'Model': ['SVM', 'SGD', 'RandomForest', 'MLP'],
    'Train-test split': [
        f"{svm_tt:.2%}",
        f"{sgd_tt:.2%}",
        f"{rf_tt:.2%}",
        f"{mlp_tt:.2%}"
    ],
    'Cross-validation': [
        f"{svm_cv:.2%}",
        f"{sgd_cv:.2%}",
        f"{rf_cv:.2%}",
        f"{mlp_cv:.2%}"
    ]
})
print("\nStudio Activity 7: Other Classifiers Summary Table")
all_models_summary

Studio Activity 7: Other Classifiers Summary Table

          Model Train-test split Cross-validation
0           SVM           89.75%           89.51%
1           SGD           86.98%           84.02%
2  RandomForest           88.37%           87.18%
3           MLP           88.09%           88.42%

# Step 5: Model Selection

In [127]:
# Filter out 'N/A' values and convert percentages to floats
svm_valid = svm_summary[svm_summary['Train-test split'] != 'N/A']
svm_best_idx = svm_valid['Train-test split'].str.rstrip('%').astype(float).idxmax()
best_svm_model = svm_summary.iloc[svm_best_idx]

best_overall_model = all_models_summary.iloc[all_models_summary['Train-test split'].str.rstrip('%').astype(float).idxmax()]

print(f"\nBest SVM Model:\n{best_svm_model}")
print(f"\nBest Overall Model:\n{best_overall_model}")

Best SVM Model:
SVM model            1 and 2 with hyperparameter tuning
Train-test split                                 90.58%
Cross-validation                                 90.00%
Name: 2, dtype: object

Best Overall Model:
Model                  SVM
Train-test split    89.75%
Cross-validation    89.51%
Name: 0, dtype: object